sudo: false
language: python
python: 3.5
cache:
  directories:
    - "$HOME/.tox"
before_cache:
  - rm -f $HOME/.tox/$TOXENV/log/*.log
env:
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=flake8
install:
  - travis_retry pip install -q tox
script:
  - tox
